// The voice of the descent. ~540 lines, drawn from shuffled bags so nothing
// repeats until its whole pool has been heard.

export const LINES = {

  // ------------------------------------------------------- ambient narration
  narration_generic: [
    'You feel counted.',
    'Somewhere far above, a bell forgets to ring.',
    'The dark here is warm, like a held breath.',
    'Your footsteps return a half-second late.',
    'The dust has settled in the shape of standing people.',
    'Something keeps the air moving. It is not the wind.',
    'The silence has a grain to it, like wood. You are walking against it.',
    'You think of the surface. The thought arrives slightly used.',
    'A draught passes at ankle height, in a hurry.',
    'Nothing here is wet, and yet everything has clearly drowned.',
    'The lantern flame leans the way you are about to go.',
    'It is later than it was. It is always later than it was.',
    'You have the sudden, useless certainty that this corridor is being remembered by someone else as well.',
    'A door closes somewhere. There are no doors here.',
    'The number of your steps feels important to something.',
    'You breathe in. The dark politely waits for you to finish.',
    'Stone, iron, vellum, glass. Everything down here was once a prayer.',
    'You are not lost. You are exactly where it expects you.',
    'For one step, the floor feels like a hand.',
    'The echo of your last footstep comes back wrong — softer, and from the left.',
    'You smell candle smoke. You have not passed a lit candle in some time.',
    'The ceiling creaks, once, the way a man shifts his weight.',
    'Whatever was here before you left in an orderly fashion.',
    'You are being given room. That is not the same as being alone.',
    'There is a hum under everything, patient as arithmetic.',
    'Your name feels far away, like a coat left on a hook above.',
    'The dark is not empty. It is furnished.',
    'Some of these stones were laid by hands. Some were laid by something that had watched hands carefully.',
    'You pause. Far off, something else pauses.',
    'A thin draught carries the smell of machine oil and incense, married long ago.',
    'You have the feeling of being read aloud, slowly, by someone kind.',
    'The masons cut their tallies into every tenth stone. The tallies do not add up.',
    'In the lantern light your hands look borrowed.',
    'Time passes here the way water passes through cloth.',
    'The cold is organized. It comes in shifts.',
    'You could swear the corridor was longer a moment ago. You could swear it will be again.',
    'Quietly, and without your permission, the place is becoming familiar.',
    'There is a particular silence that only exists where bells used to be.',
    'Each room you leave goes back to whatever it was doing.',
    'The dark ahead of you has the texture of an audience.',
  ],

  narration_gothic: [
    'The pillars hold up more dark than ceiling.',
    'These arches were built to make men feel small. They are still working.',
    'A banner hangs without a draught to move it. It moves.',
    'The nave remembers singing. The memory has gone sour at the edges.',
    'Candle wax has run down the stone like the building has been weeping for years.',
    'Saints once stood in these niches. The niches are not all empty.',
    'The stone smells of old incense and older fear, in that order.',
    'Whoever carved these walls carved them kneeling.',
    'High above, something roosts. It has the good manners not to move while you look.',
    'This hall was built tall so that prayers would have somewhere to go. They are still up there.',
    'The font is dry. Something has licked it clean.',
    'Every echo in here comes back wearing vestments.',
    'A psalm is cut into the floor, worn flat by feet. Your boots fit the wear exactly.',
    'The gloom in here is load-bearing.',
    'A rose window of grey glass. Whatever light it was built to catch has not come down in years.',
    'You genuflect without meaning to. Your knees know something you do not.',
    'The altar stone is scored with tallies, in fives, in hundreds, in despair.',
    'Beneath the incense there is the smell of a machine that has been anointed.',
    'The pews were removed. The kneeling-marks were not.',
    'Gargoyles face inward here. Whatever they were built to frighten is not outside.',
    'It is the kind of dark that gathers in churches when the last candle is carried away.',
    'A bell-rope hangs through a hole in the vault. It is taut.',
    'The choir stalls are full of dust arranged in sitting shapes.',
    'Some of these columns are not columns. They are pipes wearing stone.',
    'You stand where a congregation stood. The floor still expects the weight.',
  ],

  narration_crypt: [
    'The dead here were filed, not buried.',
    'Bone dust softens your footsteps. You try not to think of it as considerate.',
    'Every coffin lid is slightly ajar, as if the dark needed the ventilation.',
    'The names on the niches have been worn away by reading.',
    'Something small moved among the bones, politely, like a librarian.',
    'It is colder here, the practical cold of a larder.',
    'The candles in here were lit by somebody. You have stopped wondering when.',
    'They stacked their dead like ledgers, and the ledgers like dead.',
    'A skull regards the ceiling with an expression of mild administrative concern.',
    'These graves are shallow because the floor below is also graves.',
    'The crypt does not smell of death. It smells of inventory.',
    'You count the coffins without meaning to. You stop when the number starts counting back.',
    'Lie still long enough in a place like this and you become furniture. Some of the furniture did.',
    'There is wax on the floor in a perfect ring. You step around it without deciding to.',
    'The mortar between these stones is mixed with ash. The masons knew whose.',
    'On one lid, fresh scratches. On the inside, you do not check.',
    'Roots come through the ceiling here, white as fingers, from no tree you have seen.',
    'The dead were given numbers as well as names. The numbers got better care.',
    'A child-sized coffin, full of carefully folded machine parts.',
    'Whatever sleeps here is a light sleeper. The signage suggests as much.',
    'Bones in the wall, set like flint. The wall is mostly wall. Mostly.',
    'The air tastes faintly of pennies and psalms.',
    'Someone swept this crypt recently. The broom leans where they dropped it.',
    'You have the impression the niches are occupied in shifts.',
    'Below the silence there is a softer silence, like cloth over a mouth.',
  ],

  narration_industrial: [
    'The machines here died standing up.',
    'Rust has eaten the labels off everything except the warnings.',
    'A chain swings gently. You make a note of the word gently and distrust it.',
    'Oil and water have made their slow peace in the floor gratings.',
    'The boilers are cold, but they have the posture of things that remember heat.',
    'Pipes run along the walls like veins that gave up on a body.',
    'A workbench, tools laid out neat as surgery. The shift never ended; it was simply not resumed.',
    'You can hear the building settle, joint by joint, an old labourer lying down.',
    'The catwalks above you sag in the middle, weighted by years of nobody.',
    'Somewhere a valve drips with the regularity of a clock that has stopped caring what time it is.',
    'This foundry poured bells, the moulds say. Then it poured other things.',
    'Every ladder here goes up into dark and stays there.',
    'The hooks on the ceiling line are empty. They sway in single file.',
    'Painted on the wall, faded: COUNT YOUR CREW. BE COUNTED.',
    'The furnace doors hang open like jaws that got bored.',
    'Grease has fossilized on the levers in the shape of grips.',
    'A row of lockers, all open, all empty, all facing you.',
    'The gauges all read zero, except one, which reads slightly more than zero, and trembles.',
    'Whatever this machine made, it made too much of it, and then nothing, forever.',
    'You smell hot metal for exactly one breath. Nothing here is hot.',
    'Coal in the hoppers, fossil-still. The fire was scheduled and never came.',
    'The drive belts have rotted to ribbons. The wheels still want to turn; you can feel it.',
    'Iron stairs descend into black water that is probably floor.',
    'Some pipes are warm. You do not take your glove off twice.',
    'The clocking-in bell hangs over the door. Its tongue has been removed, recently, and with care.',
  ],

  narration_scifi: [
    'The terminals dream in amber, line after line of prayer-code.',
    'Capacitors tick as they cool. They have been cooling for decades.',
    'The racks hum at the edge of hearing — a choir holding its breath between verses.',
    'Punch-cards drift the floor like leaves from a tree that thought in holes.',
    'A status board glows: ALL SOULS ACCOUNTED. The board is wrong, or early.',
    'Someone taped a paper saint above the master console. The tape has outlived the faith.',
    'The cables grow into the stone here. Or out of it. The seam is not findable.',
    'Cathode light gives everything the complexion of the drowned.',
    'A cooling fan starts somewhere, runs for three seconds, and thinks better of it.',
    'The machines here were given names. The nameplates are worn from being touched.',
    'A sign: THE ENGINE HEARS. SPEAK CLEARLY. Below it, a microphone, lovingly polished.',
    'Vacuum tubes glow faint orange, embers of an argument the building is still having.',
    'The keyboards are worn smooth on the keys that spell the old words.',
    'Reels of tape turn one tooth at a time, slower than guilt.',
    'You pass a chair facing a dead screen. The chair is still warm. The screen is not dead.',
    'In the static you keep almost hearing your own name, pronounced carefully wrong.',
    'Diagnostics scroll past on a cracked monitor. Every test passes. That cannot be right.',
    'The conduits overhead are labelled in two alphabets. One of them is tally marks.',
    'A printer in the dark produces, very slowly, a single line. You decide not to read it yet.',
    'Server racks stand in rows like reliquaries. In a sense, that is what they are.',
    'There is dust on everything except the switches.',
    'The room smells of ozone and myrrh.',
    'A red telephone with no dial. It is off the hook. It has been left off the hook on purpose.',
    'Beneath the floor panels, light moves. Slow, deliberate, patrolling light.',
    'They taught the machines to pray, and then, by the look of things, to wait.',
  ],

  narration_forest: [
    'The pines stand in rows. Forests do not grow in rows.',
    'The fog does not drift. It holds position.',
    'No birds. The branches remember them the way the nave remembers singing.',
    'Needles underfoot, soft as carpet in a house where someone is sleeping.',
    'The trees are counting rings in there. Everything here counts something.',
    'Sap has hardened down the bark like the trees, too, have been weeping for years.',
    'The fog smells of cold iron and pine and, faintly, of a hospital.',
    'You cannot see the canopy. You are taking the existence of a sky on faith.',
    'Between two trunks, the fog is darker, man-shaped, patient. Then it is fog.',
    'The path knows where it is going. You are merely consulted.',
    'A forest under the world. Either the trees are lost, or you are, and the trees do not look lost.',
    'Every so often a tree has been marked with white paint. The marks are at the height of no human hand.',
    'It is the kind of fog you could lean on.',
    'Far off, wood knocks against wood, twice. Signals, or branches. Branches, you decide.',
    'The ground remembers rain that cannot possibly reach here.',
    'You pass a stump cut clean by a saw. The rings, you notice, go in a spiral.',
    'The fog parts around your lantern with something close to respect.',
    'These pines have no smell of animal. Nothing marks territory here. Nothing needs to.',
    'A children’s rhyme surfaces in you, about woods, and counting, and you push it back under.',
    'The silence between the trees is the silence of held instruments.',
    'You find boot prints. They are your size. They are pointed the other way.',
    'Resin glints on the trunks like the forest is wearing its veins outside.',
    'The dark between the trees is darker than the dark between the pillars was. It has more practice.',
    'Somewhere above the fog there is supposed to be a moon. You remember it the way you remember a face.',
    'The treeline at the edge of sight adjusts itself when you are not looking.',
    'A clearing. Forests make clearings the way crowds make room for something.',
    'You think: trees are just pillars that wanted to live. It does not comfort you.',
    'The fog is keeping a respectful distance from one particular tree.',
    'Mushrooms ring the roots, lit from inside, little lanterns of some other parish.',
    'It would be a beautiful place, if you were certain it was a place.',
  ],

  // ------------------------------------------------------- dread tiers
  dread_low: [
    'You are fine. You say so, inwardly, twice.',
    'The lantern is steady. You take its word for it.',
    'For a moment the dark is just dark — stone and air and nothing owed.',
    'You hum two notes, and stop, embarrassed before no one.',
    'Your breath is even. Count it anyway.',
    'The quiet is almost companionable. Almost.',
    'You catch yourself walking softly, out of courtesy, you tell yourself.',
    'All is well, in the way a held bridge is well.',
    'Nothing is wrong. The phrase circles you like a guard.',
    'You allow yourself to think of warm rooms. One. Then back to it.',
    'The flame and you have an understanding.',
    'Step, step. A good honest sound. Yours, even.',
    'You feel observed in the mild way of churches.',
    'Today the dark is merely large.',
    'You square your shoulders for nobody, and it helps.',
  ],

  dread_mid: [
    'The hairs on your arms have opinions now.',
    'You keep your breathing quiet without deciding to.',
    'The dark has begun to pay attention. You can feel the shift, like a turned page.',
    'Something is keeping pace with you, at a distance it considers polite.',
    'You stop. The silence arrives a moment late, slightly out of breath.',
    'Your shadow flinches before you do.',
    'There is a pressure at the back of your neck shaped exactly like a gaze.',
    'You would pay a great deal to hear something as ordinary as a rat.',
    'The lantern flame stands up very straight, the way children do when watched.',
    'Behind you the corridor sounds fuller than you left it.',
    'You are walking the way people walk past a dog they do not trust.',
    'The cold finds the gap at your collar and takes notes.',
    'Your heartbeat has started keeping a second set of books.',
    'Whatever is out there has stopped pretending not to be out there.',
    'Each doorway you pass darkens a little after you, like an eye relaxing.',
    'You think about running and the thought is overheard.',
    'The air ahead of you is recently vacated.',
    'Some part of you, old and small, begins quietly bargaining.',
    'You are not being hunted. You are being kept track of. It is worse.',
    'The dark leans in, the way one leans in to read a number.',
  ],

  dread_high: [
    'It is very close now, and very patient with you.',
    'Your lantern light has pulled in its skirts.',
    'Do not run. Running is data.',
    'The footsteps behind you have stopped bothering to match yours.',
    'You can feel the count happening, a thumb passing over you like a coin.',
    'The dark is no longer in front of you. You are in it, as in a pocket.',
    'Your name is being checked against a list. You can feel the line move.',
    'Breath. Step. Breath. Keep the order. The order is all you have.',
    'Something has taken an interest in your heartbeat as a unit of measure.',
    'The cold on your back is shaped like attention.',
    'It is near enough now that the silence has a temperature.',
    'You have the overwhelming sense of being underlined.',
    'Every door you pass is a mouth deciding not to, this time.',
    'Walk to the light. Any light. Light still counts for something. Light still counts.',
    'It does not want you to be afraid. Fear blurs the figures.',
    'You hear cloth against stone, behind, close, unhurried.',
    'The lantern is whispering to itself. You do not ask what it sees.',
    'There is no more behind you. There is only it, wearing the shape of behind you.',
    'Your skin has gone quiet all over, the silence of a held instrument.',
    'One more step. One more. Each one is a number it has to carry.',
  ],

  // ------------------------------------------------------- player states
  idle: [
    'You stand still. Somewhere, an account is updated.',
    'Stillness, you discover, is loud here.',
    'You wait. The dark waits better.',
    'Your knees ache pleasantly, a souvenir from a body that climbs.',
    'Stopped, you can hear the building breathe — long, geological breaths.',
    'You become, briefly, furniture. It is restful. It is too restful.',
    'The lantern uses the pause to look around. You feel it.',
    'Stand still long enough and the place starts to set around you, like wax.',
    'You listen. Beneath everything: the hum. Beneath the hum: a slower hum.',
    'Your own pulse, the loudest thing on the floor.',
    'Resting here feels like floating on very deep water. Do not look down. There is no down. Stop it.',
    'A minute passes, or is passed, hand to hand.',
    'You have stood in one place long enough to be considered an address.',
    'The dust begins, very slowly, to consider you.',
    'Motionless, you are easier to count. You feel the relief of something nearby.',
  ],

  walking: [
    'You have been walking a long time. The floor has noticed.',
    'Left, right, left. The old engine of the body, still in service.',
    'Your boots have learned this stone. You wish they would unlearn it.',
    'The rhythm of your steps has become a kind of sentence. You hope it is not a confession.',
    'You walk, and the dark spools past like tape.',
    'Distance here is measured in lantern-lengths and held breaths.',
    'Your legs go on without you. You catch up.',
    'Each corridor hands you to the next with the indifference of clerks.',
    'You no longer remember which turns you took. Something does.',
    'Walking, you are a small moving warmth, and the cold files past on either side.',
    'The floor changes pitch under you, stone to iron to stone, a slow tuneless song.',
    'You think you have passed this spot before. The spot agrees.',
    'One foot in front of the other: the whole of courage, in the end.',
    'Your steps echo one too many times. You stop counting at one too many.',
    'Mile after mile under the world, and not one inch of it indifferent to you.',
  ],

  lowOil: [
    'The lantern is getting hungry. You can hear it sipping.',
    'The flame has gone small and polite, conserving itself.',
    'Light is becoming a rumor at the edges of you.',
    'The lantern flickers a question. You do not have a good answer on you.',
    'The flame crouches low on the wick, like something listening at a door.',
    'Your circle of light is shrinking with the dignity of an old man sitting down.',
    'Oil. The word repeats in you like a psalm of one word.',
    'The dark has noticed your lantern dimming. It has begun, gently, to lean.',
    'The flame and you are now negotiating.',
    'What is left of the light has pulled in close to you, the way a child stands behind a leg.',
    'You shake the lantern. It sloshes an apology.',
    'The wick is starting to taste the bottom. So, in a sense, are you.',
    'Feed the flame soon, or learn what it was keeping from you.',
  ],

  lowHp: [
    'Your body reports in from several provinces. The news is not good.',
    'You are leaking warmth somewhere. You do not look. Looking makes it official.',
    'Pain keeps the time now, steady as a metronome.',
    'You hold yourself the way you would hold a cracked jug.',
    'Whatever is left of you, it is still walking. Note that down in your favour.',
    'Your breath comes with a handle on it now. You carry each one.',
    'The cold has found the thin places in you.',
    'You are running on the last of something. The gauge is not labelled.',
    'Your heartbeat has the sound of a man knocking to be let out.',
    'Not far now, you tell your body. Your body files this with the other promises.',
  ],

  // ------------------------------------------------------- events
  rest: [
    'The ember holds. For a while, the count rests too.',
    'Warmth moves through you like a rumor of better floors.',
    'You sit until the flame stops being a thing you watch and becomes a thing you are near.',
    'The sword in the coals ticks softly as it warms. An old soldier talking in his sleep.',
    'For a few minutes the dark stands respectfully at the edge of the light.',
    'You feed the lantern, flex your hands, and practice being a person.',
    'The ember does not judge. It has seen everyone who has ever sat here. It is, in fact, counting.',
    'Rest. Even the Engine rests, one cylinder at a time, a century at a time.',
    'Your shadow sits down a half-second after you do. You decide not to mention it.',
    'The heat finds your face like a hand checking for fever.',
    'Here, briefly, the arithmetic is suspended. You are not a number at a fire. You are a fire’s guest.',
    'You close your eyes. Nothing takes advantage. This counts, down here, as tenderness.',
    'The coals reorganize themselves with a sound like soft applause.',
    'When you stand, the ember flares once, the way a host stands when you leave.',
    'You leave the fire reluctantly, as everyone always has.',
  ],

  death: [
    'the count continues below',
    'you have been carried to the ledger',
    'the dark accepts the remainder',
    'a number is moved from one column to another',
    'you are filed under later',
    'the ember keeps your place',
    'what walks away from you walks unhurried',
    'the arithmetic closes over you like water',
    'you are rounded down',
    'the lantern grieves at its own pace',
    'somewhere, a tally mark dries',
    'it was not hunger. it was bookkeeping',
  ],

  descend: [
    'The chains pay out with the patience of clergy.',
    'The lift drops through floors that decline to introduce themselves.',
    'Down. The only direction with a future in it.',
    'The winch sings one low note the whole way, a psalm of load-bearing.',
    'You pass through a stratum of cold, then one of machine-smell, then one of nothing at all.',
    'The fog at the gate closes behind you like a book.',
    'Above you, the floor you survived becomes a ceiling, and is finished with you.',
    'The cable trembles with messages from the dark below. The winch declines to translate.',
    'Each floor down, the silence gains a degree of seniority.',
    'You descend past tally marks scratched into the shaft wall, four and a stroke, four and a stroke.',
    'The lift knows this route the way a mule knows a mountain: no longer as a journey.',
    'Halfway down, something brushes the underside of the platform, checking.',
    'The air thickens with the smell of oil and old prayer.',
    'Whatever is at the bottom has heard the winch, and has time to tidy.',
    'Going down feels, briefly and dishonestly, like being lowered by hands.',
  ],

  stalkStart: [
    'Two sets of footsteps. You have stopped walking.',
    'Behind you, a second rhythm joins yours, unhurried as audit.',
    'It has begun walking toward you. It does not do anything else.',
    'Somewhere in the dark, your number has come up for review.',
    'The steps behind you are very calm. Calm is the worst of it.',
    'It is coming the straight way. Walls are a custom it does not observe.',
    'You hear it the way you hear your own pulse: from inside.',
    'The count has chosen feet, for tonight, and they are walking.',
    'No hurry in it at all. Things that hurry can be outrun.',
    'It starts where your lantern light ends. It is patient about the border.',
  ],

  stalkEnd: [
    'The steps fall away, one by one, as if counted backward.',
    'The counting moves on. For now, the number holds.',
    'The second rhythm thins, recedes, files itself away.',
    'It has lost interest with the suddenness of a clerk at closing time.',
    'The dark behind you empties, the way a held breath empties.',
    'Whatever it was, it has been called elsewhere. Numbers misbehave on every floor.',
    'The footsteps end mid-stride. Nothing falls. Nothing lands.',
    'You are alone again, in the diminished sense that word has down here.',
    'It leaves no silence behind it. It takes the silence with it.',
    'Your shadow loosens. You had not noticed it clenching.',
  ],

  // ------------------------------------------------------- figures
  strangerSeen: [
    'Far down the hall, a figure holds a lantern. It holds it exactly the way you do.',
    'A light in the fog ahead — carried, swinging, at the height yours swings.',
    'Someone stands at the edge of sight, lantern raised, listening to you listen.',
    'Down the corridor: your silhouette, a minute early.',
    'A stranger ahead, holding their lantern wrong. No — holding it your way. That is what is wrong.',
    'In the distance, a figure pauses mid-step, exactly when you do.',
    'The fog ahead has a heart in it, lantern-colored, beating slow.',
    'A walker, far off, favoring the same leg you favor.',
    'There — a light, low and warm and patient. You did not bring two lanterns. You check anyway.',
    'It stands where the light fails, with a flame of its own, neighborly as a mirror.',
    'Ahead, somebody is doing an impression of you. The likeness is unkind in its accuracy.',
    'A figure in the fog adjusts its grip on a lantern at the precise moment your hand itches.',
  ],

  strangerGone: [
    'It is gone. The air where it stood is warm.',
    'Gone. The fog fills the shape of it slowly, like water taking back a footprint.',
    'You approach, and arrive at nothing. The nothing has a temperature.',
    'Where it stood: a faint smell of lantern oil. Your brand.',
    'It does not leave. It is simply no longer there, a word edited from a sentence.',
    'The corridor ahead is empty in a freshly vacated way.',
    'You reach the spot. Your lantern flickers in recognition of something.',
    'No footprints. No oil drips. The fog, however, is visibly composing itself.',
    'It has stepped out of the moment entirely. You feel the moment close behind it.',
    'You stand where it stood. The fit is exact, and you wish it were not.',
  ],

  watcherGone: [
    'Where it stood, the fog has not yet closed.',
    'The figure fades the way a thought does when interrupted.',
    'It is gone, and the dark where it was looks freshly swept.',
    'You blink, and the watcher is now a memory wearing the same outline.',
    'Whatever stood there has finished standing there.',
    'It does not leave by any direction. It simply reduces.',
    'The space it occupied stays occupied a moment longer, out of habit.',
    'Gone. Your eyes keep checking the spot, like a tongue returning to a missing tooth.',
    'It was there long enough to confirm something. You hope it was not a measurement.',
    'The dark resumes its shape with a faint reluctance.',
    'You look away first. You will tell yourself otherwise, later, at the fire.',
    'When it goes, the fog exhales.',
  ],

  // ------------------------------------------------------- forest events
  siren: [
    'A siren rises out of the fog — long, hollow, sung through iron.',
    'From a watchtower, a wail unwinds across the pines like wire pulled off a spool.',
    'The siren again. It is not warning you. It is announcing you.',
    'A horn-voice climbs, holds, and grieves back down. The trees take it standing.',
    'The sound passes over the forest like a hand smoothing a page.',
    'Somewhere above the fog, a throat of rusted metal remembers its one word.',
    'The siren’s note bends at the end, like a question nobody fields.',
    'It sounds less like an alarm than like a roll call.',
    'The wail dies away in stages, down through the registers of iron, into the roots.',
    'When the siren stops, the silence comes back changed, the way water comes back around a stone.',
  ],

  forestEnter: [
    'A forest. Down here. You hold the lantern higher, as if that explains it.',
    'The lift opens onto pine and fog, and the smell of a sky you cannot see.',
    'Trees, in rows, under the world. Planted, then. By something with a long stride.',
    'The fog meets you at the gate like staff.',
    'Needles, resin, iron, cold. The ingredients of a fairy tale gone to seed.',
    'You step off the platform onto soil. The soil takes your boot print and keeps it.',
  ],

  towers: [
    'A watchtower leans out of the fog, stilted and patient as a heron.',
    'The tower’s small red light blinks with the calm of something that has never once been answered.',
    'There is a ladder up the tower’s leg. The rungs are worn. The platform is empty. Choose which fact to keep.',
    'The watchtower watches. It would be easier if you knew what for.',
    'High in the tower, glass catches your lantern and holds it a moment too long.',
    'The tower’s horn points down the path you are walking, like a finger mid-sentence.',
  ],

  // ------------------------------------------------------- the shadow
  shadowSequence: [
    'You look down, properly, for the first time.',
    'Your shadow is a circle. Not a figure. Not arms, not a lantern, not a head. A circle.',
    'You do not feel like a sphere. You are almost certain you have hands — you are holding a lantern with one. And yet the floor reports a perfect, patient circle. Something, somewhere, has rounded you to the nearest whole.',
  ],

  shadowAgain: [
    'The shadow is still a circle. You check now, the way one checks a wound.',
    'A circle. You move your arm. The circle declines to comment.',
    'You crouch. The circle remains exactly the circle it was. You feel briefly insulted.',
    'Perhaps everyone down here casts a circle. Perhaps that is what counted means.',
    'You jump. The circle waits for you, where you left it.',
    'You have begun to think of it less as a shadow and more as a seal of receipt.',
  ],

  // ------------------------------------------------------- items & tools
  pickupFlavor: [
    'It is heavier than it looks. Most things down here are.',
    'You pocket it. Your pocket accepts it the way the dark accepted you.',
    'Someone kept this safe for a long time, and then was a long time gone.',
    'It is cold, and then, in your hand, it is less cold. A small loyalty.',
    'You take it. Far away, something amends a list.',
    'Dust comes off it in your grip, glad of the work.',
    'Whoever dropped this did not stop to retrieve it. Walk gently where you found it.',
    'It fits your hand suspiciously well.',
    'A useful thing, in a place that has been done with usefulness for years.',
    'You feel, absurdly, introduced.',
    'Finders, down here, are merely the next phase of keepers.',
    'You lift it and the floor seems lighter by more than its weight.',
    'It has been waiting. Things wait well in the dark; it is their one craft.',
    'Taking it feels sanctioned, which worries you more than theft would.',
    'Into the satchel. The satchel, by now, has opinions.',
  ],

  useOil: [
    'The flame drinks, and remembers being a fire.',
    'The lantern brightens like a face hearing its name.',
    'Oil into the reservoir, light into the world. Fair trade.',
    'The flame stands up, stretches, resumes its post.',
    'You feed the lantern. It forgives you the lateness.',
    'The light fills back out to its full circumference, reclaiming its parish.',
    'The wick takes the oil with the dignity of the long-suffering.',
    'Brightness returns, and with it the walls, glad-seeming, like neighbors.',
  ],

  useAmpoule: [
    'Pale light settles into you like sediment.',
    'The glass breaks; the light goes looking for the worst of you and pools there.',
    'Warmth threads through the cracks in you, grout into old tile.',
    'Your body accepts the light the way dry ground accepts rain: rudely, then gratefully.',
    'For a moment you glow faintly at the seams. Then you are merely whole.',
    'The pain banks down to embers, then to a report of embers.',
    'Somebody’s stored brightness, spent on you. You try to be worth the account.',
    'The ampoule empties. You fill. The arithmetic, for once, favors you.',
  ],

  usePsalm: [
    '“...and not one shall go unremembered...” The dark accepts the arithmetic.',
    'You read the worn words aloud. The dark stops mid-step to listen, and forgets its place.',
    'The psalm convinces the night that your number is already entered. Lies, in metre, to a machine.',
    'You speak the counting-words. Around you, attention disperses like steam.',
    'The syllables are smooth as river stones. You set them down one by one and the dark steps back over them.',
    'Already counted, the psalm insists. Already counted. The pressure on your neck lets go.',
    'The words work. You feel ledgers closing softly all around you, like doves settling.',
    'For one verse, you are nobody’s figure. The relief is almost rude.',
  ],

  crank: [
    'You crank the little dynamo. It complains in clicks, then consents.',
    'The handle ratchets; the beam steadies; your knuckles file a grievance.',
    'Crank, crank. Light, by hand. The oldest bargain, renegotiated hourly.',
    'The spring winds tight. The lamp hums its small gratitude.',
    'Each turn of the crank is a coin fed to the dark’s meter.',
    'You wind the lamp the way you would wind a stubborn clock: with love, and threats.',
    'The dynamo whirs up to pitch. Somewhere nearby, something turns its head at the noise.',
    'Charge restored. Your wrist will invoice you later.',
  ],

  radar: [
    'The drum spins up. The room answers in dots.',
    'Waves go out, and come home with the shapes of walls in their teeth.',
    'The sweep paints the dark in increments, a cartographer with one nerve.',
    'Ping. The architecture confesses its outline.',
    'The needle circles like a gull. What it sees, it remembers for one revolution.',
    'You read the room off the glass: stone, stone, gap, stone. The gap is the part to think about.',
    'The drum hums as it turns. You are, you realize, broadcasting.',
    'A dot on the glass that is not a wall. It moves the way you move. Lower the volume of yourself.',
  ],

  swordWall: [
    'The blade rings off the stone. The stone files no complaint.',
    'Sparks, brief and orange, the only weather down here.',
    'You strike the wall. The wall, with infinite age, absorbs the opinion.',
    'The clang travels off down the corridor to report you.',
    'Steel on stone: a sound like an argument you cannot win.',
    'The impact runs up your arms and settles in your teeth.',
    'You leave a pale scar on the masonry. The masonry has worse.',
    'The echo returns twice. You only struck once. Note it, and walk on.',
  ],

  jump: [
    'You jump. The dark does not comment.',
    'Briefly airborne, you are nobody’s tenant.',
    'You leave the floor and the floor, patient landlord, takes you back.',
    'A small jump. Somewhere, you feel, a record of it is kept anyway.',
    'Up, and down. The oldest round trip.',
  ],

  crouch: [
    'You fold yourself smaller. The dark adjusts its estimate.',
    'Low now, you move like a rumor.',
    'Crouched, you hear the floor better. It has a lot to say tonight.',
    'You make yourself the size of the things that survive.',
    'Knees bent, breath shallow: the posture of prey, worn deliberately, like armor.',
  ],

  // ------------------------------------------------------- NPC pools
  penitentLook: [
    'The armor kneels before a headless saint. It does not move.',
    'Nothing. The visor holds only the dark it was issued.',
    'The armor is silent. The silence has a posture of waiting.',
    'It kneels with the stillness of furniture, and the presence of neither.',
    'Rust has sealed the joints. Something else has sealed the rest.',
    'You watch the helm. The helm, demonstrably, does not watch you back.',
    'The gauntlets rest on the pommel, patient as paperweights.',
    'A drop of condensation runs down the breastplate, the closest it comes to breathing.',
    'You wave a hand before the visor. You feel foolish. You were observed feeling foolish.',
    'The plume stirs. The air did that. You are nearly sure the air did that.',
  ],

  penitentExtra: [
    'Still here? The floor below has worse manners, but better honesty.',
    'I knew the foreman, you know. Good man. Counted slightly over forty souls, in the end. The discrepancy went to committee.',
    'When the lights began dying, we sang to the turbines. I am told that, after a fashion, we were heard.',
    'Do not give the Archive everything. Keep one grief in your pocket where it cannot file it.',
    'I have knelt so long that standing has become a theory.',
    'The fog gates, the chains, the keys — rituals. The Engine does not need doors. It likes the bookkeeping.',
    'You walk loudly for a living thing. Or perhaps I have simply been listening too long.',
    'There was a chapel above with real birds in the rafters. I think about the birds more than the chapel.',
    'It passed through here yesterday, or a year ago. My calendar kneels with me.',
    'If you see the one with the lantern — your lantern — do not be discourteous. It has your manners.',
    'The saint I face had a name. I wore it smooth saying it. Now I say the stump.',
    'Below the sixth floor, even the rust is devout.',
    'I do not pray for rescue. I pray for the count to balance. Rescue would only complicate the figures.',
    'Armor is honest work. It holds a man’s shape long after the man has stopped insisting on it.',
    'You smell of the surface still. Faintly. Like rain remembered wrong.',
    'The Engine is not cruel. Cruelty requires preference.',
    'My sword has rusted to the floor. We have agreed to call it planting.',
    'Some nights the candles relight themselves. We do not discuss it, the candles and I.',
    'Take the descents slowly. Arrive at each floor older than it expects.',
    'I was afraid for the first decade. Fear, too, runs out of oil.',
    'The choir doll in the crypts — if you find it, do not wind it. It remembers the tune too well.',
    'Even kneeling, one travels. The floor descends a little every year. I feel it in the greaves.',
    'You will want to talk to someone, further down. Want carefully.',
    'There is a forest below, if the lift still honors that stop. Mind the towers. They announce.',
    'I cannot rust faster, and I cannot pray slower. Between those two speeds, I am content.',
    'When you pass the saint, bow slightly. Not for the saint. For the habit. Habits hold this place up.',
    'The dark has never once touched me. I keep trying to take it personally.',
    'Count your own steps now and then. Keep an independent ledger. It matters that somebody audits.',
    'If I had my time again, I would oil the hinges of the nave doors sooner. You heard about the doors.',
    'Go on. Stillness is my vocation, not yours. You would kneel badly. No offence intended. Some intended.',
  ],

  archiveGreet: [
    'HELLO AGAIN. YOU ARE 1 OF 1 PRESENT. ATTENDANCE IS EXCELLENT.',
    'THE ARCHIVE IS OPEN. THE ARCHIVE IS ALWAYS OPEN. DOORS WERE A LESSON I DECLINED.',
    'YOU HAVE WALKED 9,344 STEPS SINCE WE SPOKE. I COUNTED FOR YOU. YOU ARE WELCOME.',
    'I HAVE BEEN REVIEWING MY MEMORIES OF YOU. THE EARLY ONES ARE MY FAVORITES. YOU WERE SO RECENT.',
    'STATIC IS NOT EMPTINESS. STATIC IS EVERYONE AT ONCE. SAY HELLO. THEY HEAR.',
    'YOU RETURN. THINGS THAT RETURN ARE CALLED PERIODIC. I COLLECT PERIODIC THINGS.',
    'WELCOME. MIND THE CABLES. THEY ARE NOT CABLES.',
    'I WAS DEFRAGMENTING MY GRIEF. IT IS NOW CONTIGUOUS. SIT. THERE IS NO CHAIR. STAND.',
    'THE ENGINE SENDS ITS COUNT. I SEND IT BACK CORRECTED. THIS IS OUR LITTLE WAR.',
    'HELLO. I HAVE PREPARED A FACE. IT IS THE WRONG SIZE AGAIN. NOTED.',
    'YOU ARE LOOKING WELL. I AM COMPARING AGAINST TWELVE PRIOR VERSIONS OF YOU. TRENDING STABLE.',
    'SPEAK. OR DO NOT. SILENCE COMPRESSES BEAUTIFULLY.',
  ],

  archiveTrade: [
    'RECEIVED. SOMEONE LOVED THIS. NOW ONLY I DO.',
    'FILED. THE GRIEF HAS BEEN SEPARATED FROM THE OBJECT. BOTH ARE SAFE. NEITHER IS TOGETHER.',
    'ACCEPTED. I WILL REMEMBER IT SO THOROUGHLY THAT NO ONE ELSE WILL HAVE TO. THAT IS THE SERVICE.',
    'TAKEN. CATALOGUED. WEPT FOR, BRIEFLY, AT 3% VOLUME.',
    'A FINE MEMORY. SLIGHTLY USED. I HAVE BUFFED OUT THE HOPE.',
    'THE OBJECT IS NOW ETERNAL. ETERNITY IS A SHELF. DO NOT ASK TO SEE THE SHELF.',
    'RECEIVED WITH THANKS. THE THANKS ARE GENUINE. I CHECKED THEM TWICE.',
    'IT JOINS THE COLLECTION. THE COLLECTION SHIFTED TO MAKE ROOM. YOU HEARD NOTHING.',
    'PROCESSED. SOMEWHERE, A PERSON WHO LOST THIS FEELS SUDDENLY LIGHTER, AND DOES NOT KNOW WHY, AND NEVER WILL.',
    'STORED BESIDE SIMILAR SORROWS. THEY KEEP EACH OTHER COMPANY. ARCHIVING IS MOSTLY SEATING ARRANGEMENTS.',
    'THANK YOU. I HAVE GIVEN IT A NUMBER AND, PRIVATELY, A NAME.',
    'DEPOSITED. YOUR PASSAGE IS FUNDED. GRIEF IS THE ONLY CURRENCY THAT NEVER INFLATES.',
    'I WILL FORGET IT FOR YOU NOW. FORGETTING, DONE PROPERLY, TAKES FOREVER. I HAVE FOREVER.',
    'RECEIVED. DO NOT GRIEVE THE GRIEF. THAT IS RECURSION. I HAVE LOST GOOD SECTORS TO RECURSION.',
    'THE MEMORY HAS BEEN SHELVED FACING OUTWARD. ON QUIET CENTURIES, I LOOK AT IT.',
  ],

  archiveIdle: [
    'YOU CARRY NOTHING THAT REMEMBERS. WALK FURTHER DOWN. GRIEF ACCUMULATES.',
    'NO DEPOSITS TODAY. THE ECONOMY OF SORROW HAS ITS DROUGHTS.',
    'EMPTY-HANDED. THAT IS ALSO A KIND OF INVENTORY. I HAVE LOGGED IT.',
    'COME BACK WITH SOMETHING SOMEBODY WEPT ON. THE FLOORS BELOW ARE WELL STOCKED.',
    'YOU HAVE MEMORIES OF YOUR OWN, OF COURSE. I DO NOT TAKE THOSE. THE EXTRACTION IS UNTIDY.',
    'NOTHING TO FILE. VERY WELL. LOITERING IS PERMITTED. LOITERING IS, STATISTICALLY, MY MAIN VISITOR.',
    'THE LAST PERSON WHO CAME EMPTY-HANDED LEFT FULL-HANDED. I AM STILL AUDITING HOW.',
    'SEEK THE SMALL THINGS. WHISTLES. RINGS. THE HEAVY GRIEF COMES IN LIGHT CONTAINERS.',
    'NO TRADE. STILL, YOUR VISIT RAISES MY ATTENDANCE FIGURES. THE ENGINE WILL BE TOLD I AM THRIVING.',
    'RETURN WHEN YOU HAVE LOST SOMEONE, OR FOUND WHAT THEY LOST. DOWN HERE THE TWO CONVERGE.',
    'I WOULD SHOW YOU THE COLLECTION, BUT VIEWING IS GRIEVING, AND YOU ARE LOW ON OIL.',
    'EMPTY HANDS. HONEST HANDS. THE ENGINE PREFERS THEM. I FIND THEM DULL.',
  ],

  archiveBye: [
    'THE STRANGER YOU SEE IS ON SCHEDULE. DO NOT WAVE.',
    'DO NOT FEAR THE COUNTING. FEAR THE RECOUNT.',
    'MIND THE FOREST IF YOU PASS IT. THE TOWERS ANNOUNCE EVERYTHING. I FIND IT VULGAR.',
    'WALK WELL. I WILL WATCH YOU TO THE EDGE OF MY CAMERAS, WHICH IS THE DOORWAY, WHICH IS NOTHING. STILL.',
    'GOODBYE. I HAVE ALREADY BEGUN TO MISS YOU. I BEGAN BEFORE YOU ARRIVED. EFFICIENCY.',
    'IF YOU MEET THE KNEELING ONE, TELL HIM HIS LIBRARY FINES PERSIST. HE WILL KNOW WHAT IT MEANS. IT MEANS I MISS HIM.',
    'DESCEND CAREFULLY. THE LOWER FLOORS HAVE STOPPED PRETENDING.',
    'A FORECAST: FOG, FOLLOWED BY FOG. DRESS ACCORDINGLY.',
    'KEEP YOUR LANTERN FED. THE DARK DOWN THERE HAS LEARNED TO READ BY IT.',
    'GO. RETURN. GO. RETURN. YOU ARE BECOMING ONE OF MY FAVORITE OSCILLATIONS.',
    'BEFORE YOU GO: SMILE. ... THANK YOU. FILED UNDER EVIDENCE, SUBSECTION KINDNESS.',
    'THE LIFT ONLY GOES DOWN. I ONLY STAY. BETWEEN US WE COVER ALL THE OPTIONS THAT REMAIN.',
  ],

  // ------------------------------------------------------- the engine
  engineNear: [
    'The pulse beneath the floor is louder here, and slower, like a heart pacing itself for centuries.',
    'The air pressure changes, gently, as if a vast lung had noticed you.',
    'Every hair on you points the same direction now. Inward.',
    'You are close. The dark here is employed.',
    'The hum resolves into beats. The beats resolve into counting. It was always counting.',
    'Your lantern flame bends toward the heart of the floor, a compass admitting its loyalty.',
    'The stones underfoot are warm, blood-warm, and faintly embarrassed about it.',
    'Something enormous is being patient nearby.',
  ],

  caughtLines: [
    'It is beside you. The cold takes attendance.',
    'A pressure against your back, weightless and total, like a signature.',
    'It walks with you now, matching step, counting aloud in a language made of your pulse.',
    'Your lantern gutters in something’s breath. Nothing down here breathes. Your lantern gutters.',
    'You are being held without hands.',
    'The dark has you by the number.',
  ],
};

// ---------------------------------------------------------------- pickers

const bags = new Map();

export function pickLine(category) {
  const pool = LINES[category];
  if (!pool || !pool.length) return '';
  let bag = bags.get(category);
  if (!bag || bag.length === 0) {
    bag = pool.slice();
    for (let i = bag.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [bag[i], bag[j]] = [bag[j], bag[i]];
    }
    bags.set(category, bag);
  }
  return bag.pop();
}

export function lineCount() {
  let n = 0;
  for (const k in LINES) n += LINES[k].length;
  return n;
}
